var word = "Kill two birds with one stone";
console.log(word[4]);
console.log(word.length > 5 && word[0] === "d");
console.log(word.length > 5 && word[0] === "s");
console.log(word.indexOf("o") > -1);
console.log(word.indexOf("z") > -1);
var str = "foggy";
console.log(str[2 + 1]);
console.log(str[str.length - 1]);
str = "foggy";
console.log(str);
console.log(str.length);
console.log(str.indexOf("ogg"));
console.log(str[2 + 1]);
console.log(str[str.length - 1]);
str = "foggy";
console.log(str);
console.log(str.length);
console.log(str.indexOf("ogg"));