let mango;
console.log(mango);
mango = 10;
console.log(mango);
mango + 1;
console.log(mango);
mango += 1;
console.log(mango);
let banana = mango;
console.log(banana);
banana = banana / 2;
console.log(banana);
console.log(mango);