var word = "swim";
console.log(word + " felicia");
console.log(word);
var num = 20;
num = num * 2;
console.log(num);
var numberOfApple = 99;
var appleLeft = numberOfApple - 1;
console.log(appleLeft);
console.log(numberOfApple);